# @package feature_extractor

_target_: sklearn.feature_extraction.text.TfidfVectorizer

# Parameters for TfidfVectorizer
min_df: 1 # Minimum document frequency
max_df: 1.0 # Maximum document frequency (proportion)
ngram_range: ${as_tuple:1,1} # Use only unigrams
# stop_words: 'english' # Example: uncomment to use stop words
# max_features: 5000 # Example: limit vocabulary size
